# Website settings
title: "Lucas Schejtman"
description: "Lucas Schejtman's personal website."
keywords: "Lucas,Schejtman,personal,portfolio"
baseurl: "/"
url: "http://lucasschejtman.github.io"
favicon: "static/img/favicon.ico?v=2"

# author
author:
  name: 'Lucas Schejtman'
  email: 'lucas.schejtman@gmail.com'
  github: 'https://github.com/lucasschejtman'
  linkedin: 'https://www.linkedin.com/in/lucas-schejtman-29300b32'
  head_img: 'static/img/landing/lucas.jpg'
  tag: 'Mathematics, Software, Sports and Video Games'
  desc: >
            Applied math enthusiast, specially cryptography, with over 10 years experience in the software industry.
            <br />As a full stack developer, I'm always up for a challenge at any front.
            <br />I enjoy keeping myself up to date and playing with the latest and greatest.

stylesheets:
  - url: "bower_components/bootstrap/dist/css/bootstrap.min.css"
  - url: "bower_components/animate.css/animate.min.css"
  - url: "bower_components/components-font-awesome/css/font-awesome.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "bower_components/jquery/dist/jquery.min.js"
  - url: "bower_components/wow/dist/wow.min.js"
  - url: "bower_components/PACE/pace.min.js"
  - url: "bower_components/bootstrap/dist/js/bootstrap.min.js"

# google analytics
ga:
  id: UA-84338948-1

# Build settings
encoding: "utf-8"
