# Website settings
title: "Joe Minicucci"
description: "Joe Minicucci's personal website."
keywords: "joe,minicucci,resume,cv,personal,portfolio"
baseurl: "/"
url: "http://joeminicucci.github.io"
favicon: "static/img/kali2.png?v=2"

author:
  name: 'Joe Minicucci'
  email: 'm64oa2b9q1r6@opayq.com'
  github: 'https://github.com/joeminicucci'
  twitter: 'https://www.twitter.com/joeminicucci'
  blog: 'https://blog.joeminicucci.com'
  head_img: 'static/img/me_circuit.jpg'
  tag: 'Information Security, Application Security, Adversary Emulation, Penetration Testing, Software Engineering'
  desc: >
    Information Security practitioner focusing on Application Security, DevSecOps, Penetration Testing, Offenseive Security Engineering and Red Teaming. My background is in Software Engineering and Computer Science. I am interested in a variety of fields also including: Wireless and Physical Security, Adversary Emulation, Software and Reverse Engineering, and linguistics. I can speak Mandarin and am currently learning German.
stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"
  - id: "blog"
    name: "Blog"
    tpl: "blog.html"
  - id: "contact"
    name: "Contact"
    tpl: contact.html

# google analytics
# ga:
  # id:

# Build settings
encoding: "utf-8"
