# Website settings
title: "Lucas Schejtman"
description: "Lucas Schejtman's personal website."
keywords: "Lucas,Schejtman,personal,portfolio"
baseurl: "/"
url: "http://lucasschejtman.github.io"
favicon: "static/img/favicon.ico?v=2"

# author
author:
  name: 'Lucas'
  first_name: 'Lucas'
  last_name: 'Schejtman'
  email: 'lucas.schejtman@gmail.com'
  github: 'https://github.com/lucasschejtman'
  linkedin: 'https://www.linkedin.com/in/lucas-schejtman-29300b32'
  head_img: 'static/img/landing/lucas.jpg'
  tag: 'Mathematics, Software, Sports and Video Games'
  desc: >
            Applied math enthusiast, specially cryptography, with over 10 years experience in the software industry.
            <br />As a full stack developer, I'm always up for a challenge at any front.
            <br />I enjoy keeping myself up to date and playing with the latest and greatest.

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  projects: 'Projects'

# my projects
projects:
  - name: 'IMDB GraphQL'
    url: 'https://github.com/lucasschejtman/imdb-graphql-flow'
    img: 'static/img/landing/graphql.png'
    desc: >
            A GraphQL wrapper for some of the unofficial IMDB APIs.
            <br />Written in ES6 with Ramda and FlowType
  - name: 'Functional React'
    url: 'https://github.com/lucasschejtman/react-redux-functional'
    img: 'static/img/landing/react.png'
    desc: >
            A functional and modular approach to the well known todo app.
            <br />Written in ES6 with React, Redux and Ramda
  - name: 'Online Problems'
    url: 'https://github.com/lucasschejtman/online-problems'
    img: 'static/img/landing/haskell.png'
    desc: >
            My solutions to problems from sites such as; Project Euler, HackerRank and more.
            <br />Written in Haskell

# google analytics
ga:
  id: UA-84338948-1

# Build settings
encoding: "utf-8"
