# Website settings
title: "Joe Minicucci"
description: "Joe Minicucci's personal website."
keywords: "joe,minicucci,resume,personal,portfolio"
baseurl: "/"
url: "http://joeminicucci.github.io"
favicon: "static/img/kali2.png?v=2"

author:
  name: 'Joe Minicucci'
  email: 'joeisadev@sudomail.com'
  github: 'https://github.com/joeminicucci'
  linkedin: 'https://www.linkedin.com/in/joeminicucci'
  cv: 'https://github.com/joeminicucci/resume/blob/master/Joe_Minicucci_Resume.pdf' # An online CV can be printed as PDF, leave blank if you don't have now
  head_img: 'static/img/kali2.png'
  tag: 'Software Engineering, Information Security, Wireless, Arduino, Big Data'
  desc: >
    I am a full stack engineer who strives to be a generalist, and loves to experiment with new technologies. I am interested in a variety of fields
    including: Big Data, Information Security, Network Programming, and Distributed Systems. I hope
    to foster innovation, as well as to aid Agile teams in practical software development methodologies.
stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"
  # - id: "contact"
  #   name: "Contact"
  #   tpl: contact.html

# google analytics
# ga:
  # id:

# Build settings
encoding: "utf-8"
